services:
  backend:
    build:
      context: ./backend/backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Maps port 3000 on host to port 3000 in the container
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: takeback
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234
    ports:
      - "5432:5432" # Expose PostgreSQL port for external connections if needed

volumes:
  postgres_data:
